spring:
  application:
    name: request-notification-microservice
  kafka:
    bootstrap-servers: localhost:9092

  config:
    import: "configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    function:
      definition: sendToUserStorage
    stream:
      bindings:
        sendToUserStorage-out-0:
          destination: user-storage-topic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
    hostname: localhost
