spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: request-notification-route
          uri: lb://request-notification-microservice
          predicates:
            - "Path=/request-notification/**"
          filters:
            - "StripPrefix=1"
        - id: user-storage-route
          uri: lb://user-storage-microservice
          predicates:
            - "Path=/user-storage/**"
          filters:
            - "StripPrefix=1"

server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
