spring:
  application:
    name: user-storage-microservice

  config:
    import: "configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    function:
      definition: processRequestNotification
    stream:
      bindings:
        processRequestNotification-in-0:
          destination: user-storage-topic
          group: user-storage-group
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
    hostname: localhost
